hideui singleuser,hints,badges

icons_dir themes/rEFInd-minimal-dark/icons_dark

banner themes/rEFInd-minimal-dark/background_dark.png

banner_scale fillscreen

selection_big   themes/rEFInd-minimal-dark/selection_big_dark.png
selection_small themes/rEFInd-minimal-dark/selection_small.png

menuentry "NixOS" {
    icon themes/rEFInd-minimal-dark/icons_dark/os_nixos.png
    loader /EFI/NixOS-boot/grubx64.efi
}
