hideui singleuser,hints,badges

icons_dir themes/rEFInd-darkflake/icons

banner themes/rEFInd-darkflake/background.png
banner_scale fillscreen

selection_big themes/rEFInd-darkflake/selection_big.png
selection_small themes/rEFInd-darkflake/selection_small.png